// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB63B30Ucd54woyXUoArMA5sC0MTAejhE8',
    appId: '1:778435998919:web:3ae20a578ee5127dea3ae2',
    messagingSenderId: '778435998919',
    projectId: 'pdf-sign-manager-3fda9',
    authDomain: 'pdf-sign-manager-3fda9.firebaseapp.com',
    databaseURL: 'https://pdf-sign-manager-3fda9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pdf-sign-manager-3fda9.appspot.com',
    measurementId: 'G-S54BZM9MXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDndVrD4J4rvjgvYQqO1pzVh6Z9Vg8GUio',
    appId: '1:778435998919:android:9f30a76103b5d997ea3ae2',
    messagingSenderId: '778435998919',
    projectId: 'pdf-sign-manager-3fda9',
    databaseURL: 'https://pdf-sign-manager-3fda9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pdf-sign-manager-3fda9.appspot.com',
  );
}
